[package]
name = "lp-token-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = ["Uederson de Amadeu Ferreira"]

[dev-dependencies]

[dependencies.lp-token]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.57.1"
