// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            5
// Async Callback (empty):               1
// Total number of exported functions:   7

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    reputation_score
    (
        init => init
        setOracleAddress => set_oracle_address
        updateScore => update_score
        getUserScore => get_user_score
        isEligibleForLoan => is_eligible_for_loan
        calculateMaxLoanAmount => calculate_max_loan_amount
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
