[package]
name = "lp-token"
version = "0.0.0"
authors = ["Uederson de Amadeu Ferreira"]
edition = "2021"
publish = false


[lib]
path = "src/lib.rs"

[dependencies.multiversx-sc]
version = "0.57.1"

[dev-dependencies.multiversx-sc-scenario]
version = "0.57.1"
