// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           18
// Async Callback (empty):               1
// Total number of exported functions:  20

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    erc20_token
    (
        init => init
        getName => get_name
        getTicker => get_ticker
        getDecimals => get_decimals
        totalSupply => total_supply
        balanceOf => balance_of
        transfer => transfer
        allowance => allowance
        transferFrom => transfer_from
        mint => mint_endpoint
        burn => burn_endpoint
        burnOwn => burn_own
        pause => pause
        unpause => unpause
        isPaused => is_paused
        setFeePercentage => set_fee_percentage
        getFeePercentage => get_fee_percentage
        approve => approve
        publicMint => public_mint
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
