// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            7
// Async Callback:                       1
// Total number of exported functions:   9

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    debt_token
    (
        init => init
        issueDebtToken => issue_debt_token
        createDebtNft => create_debt_nft
        mint => mint
        burn => burn
        balanceOf => balance_of
        totalTokenSupply => total_token_supply
        burnDebtNft => burn_debt_nft
    )
}

multiversx_sc_wasm_adapter::async_callback! { debt_token }
