// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           22
// Async Callback:                       1
// Total number of exported functions:  24

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    debt_token
    (
        init => init
        issueDebtToken => issue_debt_token
        createDebtNft => create_debt_nft
        burnDebtNft => burn_debt_nft
        get_loan_nft_id_for_test => get_loan_nft_id_for_test
        getCurrentFunds => get_current_funds
        status => status
        getTarget => target
        getDeadline => deadline
        getDeposit => deposit
        debtTokenId => debt_token_id_view
        mint => mint
        burn => burn
        transferTokens => transfer_tokens
        approveTokens => approve_tokens
        transferTokensFrom => transfer_tokens_from
        getAllowance => get_allowance
        increaseTokenAllowance => increase_token_allowance
        decreaseTokenAllowance => decrease_token_allowance
        balanceOf => balance_of
        totalTokenSupply => total_token_supply
        getLoanNftId => get_loan_nft_id
        getNftLoanId => get_nft_loan_id
    )
}

multiversx_sc_wasm_adapter::async_callback! { debt_token }
