name: Deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Build Smart Contracts
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build Smart Contracts
        run: |
          cd smart-contracts
          cargo build --release
      
      # Build Frontend
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build
          
      # Build and push Docker images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push Backend
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          push: true
          tags: social-ficredit/backend:latest,social-ficredit/backend:${{ github.ref_name }}
          
      - name: Build and push ElizaOS
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          file: ./backend/Dockerfile.eliza
          push: true
          tags: social-ficredit/eliza:latest,social-ficredit/eliza:${{ github.ref_name }}
          
      - name: Build and push Frontend
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          push: true
          tags: social-ficredit/frontend:latest,social-ficredit/frontend:${{ github.ref_name }}
          
      # Deploy to server
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/social-fi-credit
            git pull
            docker-compose pull
            docker-compose up -d
            docker system prune -af
