// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            7
// Async Callback (empty):               1
// Total number of exported functions:   9

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    liquidity_pool
    (
        init => init
        depositFunds => deposit_funds
        withdrawFunds => withdraw_funds
        provideFundsForLoan => provide_funds_for_loan
        receiveLoanRepayment => receive_loan_repayment
        getAnnualYieldPercentage => get_annual_yield_percentage
        getTotalLiquidity => get_total_liquidity
        getProviderFunds => get_provider_funds
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
