// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           30
// Async Callback (empty):               1
// Total number of exported functions:  32

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    liquidity_pool
    (
        init => init
        depositFunds => deposit_funds
        withdrawFunds => withdraw_funds
        withdraw => withdraw
        provideFundsForLoan => provide_funds_for_loan
        receiveLoanRepayment => receive_loan_repayment
        borrow => borrow_endpoint
        repay => repay_endpoint
        pause => pause
        unpause => unpause
        add_accumulated_interest_endpoint => add_accumulated_interest_endpoint
        distributeInterest => distribute_interest_endpoint
        useReserves => use_reserves_endpoint
        lpTokensMinted => lp_tokens_minted_endpoint
        lpTokensBurned => lp_tokens_burned_endpoint
        debtTokensMinted => debt_tokens_minted_endpoint
        debtTokensBurned => debt_tokens_burned_endpoint
        calculate_current_interest_rate => calculate_current_interest_rate
        set_interest_rate_base => set_interest_rate_base
        set_target_utilization_rate => set_target_utilization_rate
        set_max_utilization_rate => set_max_utilization_rate
        set_reserve_percent => set_reserve_percent
        setLoanControllerAddress => set_loan_controller_address
        setDebtTokenAddress => set_debt_token_address
        setLpTokenAddress => set_lp_token_address
        is_paused => is_paused
        get_token_price => get_token_price
        getBorrowerDebt => get_borrower_debt
        getAnnualYieldPercentage => get_annual_yield_percentage
        getTotalLiquidity => get_total_liquidity
        getProviderFunds => get_provider_funds
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
